from heapq import heappush, heappop

from utils import (
    print_output, 
    ListNode, 
    create_ll, 
    print_linked_list,
)

"""
# Set 4

## 1) Backspace String Compare

**Difficulty:** Easy

Given two strings `s` and `t`, return `true` if they are 
equal when both are typed into empty text editors. `'#'` 
means a backspace character.

### Example

**Input:**
`s = "ab#c", t = "ad#c"`
**Output:**
`true`

---
"""


@print_output
def backspace_string_compare(s: str, t: str):
    if not s or not t:
        return False
    def build(word: str) -> str:
        st = []
        remove = []
        for i, ch in enumerate(word):
            if ch == "#":
                if st:
                    st.pop()
                else:
                    remove.append(i)
            else:
                st.append(i)
        while st:
            remove.append(st.pop())
        res = []
        for i, ch in enumerate(word):
            if i not in remove:
                res.append(ch)
        return "".join(res)
    
    return len(build(s)) == len(build(t))


# backspace_string_compare("ab#c", "ad#c")

"""

## 2) Find the Difference

**Difficulty:** Easy

You are given two strings `s` and `t`.

String `t` is generated by random shuffling string `s` and
then adding one more letter at a random position.

Return the letter that was added to `t`.

### Example

**Input:**
`s = "abcd", t = "abcdd"`
**Output:**
`"e"`

---

"""
def get_freq(word: str) -> dict[str, int]:
    freq = {}
    if not word:
        return freq
    for ch in word:
        freq[ch] = freq.get(ch, 0) + 1
    return freq


@print_output
def find_diff_in_strs(s: str, t: str) -> str:
    if not s or not t:
        return ""
    s_freq = get_freq(s)
    t_freq = get_freq(t)

    for f in t_freq:
        if f not in s_freq or t_freq[f] != s_freq[f]:
            return f
    return ""


# find_diff_in_strs("abcd", "abcdd")

"""

## 3) Implement Queue using Stacks

**Difficulty:** Easy

Implement a first in first out (FIFO) queue using only 
two stacks.

Implement the `MyQueue` class:

* `push(x)`
* `pop()`
* `peek()`
* `empty()`

### Example

**Input:**
`["MyQueue","push","push","peek","pop","empty"]`
`[[],[1],[2],[],[],[]]`

**Output:**
`[null,null,null,1,1,false]`

---
"""

class MyQueue:
    def __init__(self):
        self.in_stk = []
        self.out_stk = []
    
    def push(self, value):
        self.in_stk.append(value)
    

    def _move(self):
        if not self.out_stk:
            while self.in_stk:
                self.out_stk.append(self.in_stk.pop())
    
    def pop(self):
        self._move()
        if self.empty():
            return -1
        return self.out_stk.pop()
    
    def peek(self):
        self._move()
        if self.empty():
            return -1
        return self.out_stk[-1]


    def empty(self):
        return not self.out_stk and not self.in_stk
    

"""

## 4) Sort Characters By Frequency

**Difficulty:** Medium

Given a string `s`, sort it in decreasing order based on 
the frequency of the characters.

### Example

**Input:**
`s = "tree"`
**Output:**
`"eert"`

---

"""


@print_output
def sort_char_by_freq(s: str) -> str:
    result = []
    if not s:
        return ""
    max_heap = []
    char_freq = get_freq(s)
    
    for k, v in char_freq.items():
        heappush(max_heap, (-v, k))
    while max_heap:
        cnt, ch = heappop(max_heap)
        cnt = -cnt
        result.append(ch * cnt)
    return "".join(result)


# sort_char_by_freq("tree")


"""

## 5) Find All Anagrams in a String

**Difficulty:** Medium

Given two strings `s` and `p`, return an array of all the
start indices of `p`'s anagrams in `s`.

### Example

**Input:**
`s = "cbaebabacd", p = "abc"`
**Output:**
`[0,6]`

---
"""


@print_output
def find_all_anagram_in_str(s: str, p: str) -> list[int]:
    if not s or len(s) < len(p):
        return []
    
    result = []
    p_freq = get_freq(p)
    left = 0
    for right in range(len(p), len(s)):
        if get_freq(s[left:right]) == p_freq:
            result.append(left)
        left += 1
    return result


# find_all_anagram_in_str("cbaebabacd", "abc")

"""

## 6) Trapping Rain Water

**Difficulty:** Medium

Given `n` non-negative integers representing an elevation 
map, compute how much water it can trap after raining.

### Example

**Input:**
`height = [0,1,0,2,1,0,1,3,2,1,2,1]`
**Output:**
`6`

---
"""


@print_output
def trapping_rain_water(height: list[int]) -> int:
    if not height:
        return 0
    water = 0
    left = 0
    right = len(height) - 1
    max_left = 0
    max_right = 0

    while left < right:
        if height[left] < height[right]:
            max_left = max(max_left, height[left])
            water += max_left - height[left]
            left += 1
        else:
            max_right = max(max_right, height[right])
            water += max_right - height[right]
            right -= 1
    return water


# trapping_rain_water([0,1,0,2,1,0,1,3,2,1,2,1])

"""

## 7) Find the Duplicate Number

**Difficulty:** Medium

Given an array of integers `nums` containing `n + 1` integers 
where each integer is in the range `[1, n]`, return the 
duplicate number.

You must solve the problem without modifying the array 
and using only constant extra space.

### Example

**Input:**
`nums = [1,3,4,2,2]`
**Output:**
`2`

---

"""


@print_output
def find_duplicate_number(nums: list[int]) -> int:
    if not nums:
        return 0
    for n in nums:
        idx = abs(n) - 1

        if nums[idx] < 0:
            return abs(n)
        else:
            nums[idx] = -nums[idx]
        

# find_duplicate_number([1,3,4,2,2])

        
"""

## 8) Remove Duplicates from Sorted List II

**Difficulty:** Medium

Given the head of a sorted linked list, delete all nodes 
that have duplicate numbers, leaving only distinct numbers 
from the original list.

### Example

**Input:**
`head = [1,2,3,3,4,4,5]`
**Output:**
`[1,2,5]`

---

"""

def remove_dup_from_sorted_ll(head: ListNode) -> ListNode:
    if head is None:
        return head
    dummy = ListNode(0)
    dummy.next = head
    curr = head
    
    prev = dummy
    while curr:
        while curr.next and curr.val == curr.next.val:
            curr = curr.next
        if prev.next != curr:
            prev.next = curr.next
        else:
            prev = prev.next
        curr = curr.next
    return dummy.next if dummy.next is not None else None
        
            


"""

## 9) Partition List

**Difficulty:** Medium

Given the head of a linked list and a value `x`, partition 
it such that all nodes less than `x` come before nodes greater 
than or equal to `x`.

### Example

**Input:**
`head = [1,4,3,2,5,2], x = 3`
**Output:**
`[1,2,2,4,3,5]`

---
"""


def partion_ll(head: ListNode, num: int) -> ListNode:
    if head is None:
        return head
    small_dummy = ListNode()
    big_dummy = ListNode()
    small = small_dummy
    big = big_dummy
    curr = head
    while curr:
        nxt = curr.next
        curr.next = None
        if curr.val < num:
            small.next = curr
            small = curr
        else:
            big.next = curr
            big = curr
        curr = nxt
    small.next = big_dummy.next

    return small_dummy.next


ll2 = create_ll([1,4,3,2,5,2])
ans_ll = partion_ll(ll2, 3)
print_linked_list(ans_ll)





"""

## 10) Queue Reconstruction by Height

**Difficulty:** Medium

You are given an array of people `people` where `people[i] = 
[hi, ki]` represents the `i`th person.

Reconstruct and return the queue.

### Example

**Input:**
`people = [[7,0],[4,4],[7,1],[5,0],[6,1],[5,2]]`
**Output:**
`[[5,0],[7,0],[5,2],[6,1],[4,4],[7,1]]`

---

"""


@print_output
def queue_recontruction_by_height(
        people: list[list[int]]
) -> list[list[int]]:
    if not people:
        return []
    people.sort(key=lambda x: (-x[0], x[1]))
    res = []
    for h, k in people:
        res.insert(k, [h, k])
    return res
    

queue_recontruction_by_height([[7,0],[4,4],[7,1],[5,0],[6,1],[5,2]])
