from collections import deque
from utils import *

"""

# 15 new questions


## 1) Backspace String Compare

**Topic:** String Manipulation, Two Pointers
**Difficulty:** Easy

Given two strings `s` and `t`, return `true` if they are equal when both are 
typed into empty text editors. `'#'` means a backspace character.

### Example 1

**Input:**
`s = "ab#c", t = "ad#c"`
**Output:**
`true`

### Example 2

**Input:**
`s = "a#c", t = "b"`
**Output:**
`false`

---
"""


@print_return_value
def equal_strings(s: str, t: str) -> bool:
    if not s or not t:
        return False
    
    def build(string: str) -> list[str]:
        st = []
        for ch in string:
            if ch == "#":
                if st:
                    st.pop()
            else:
                st.append(ch)
        return st

    return len(build(s)) == len(build(t))



"""

## 2) Implement Stack using Queues

**Topic:** Stack, Queue, Design
**Difficulty:** Easy

Implement a last-in-first-out (LIFO) stack using only two queues.

Implement the `MyStack` class:

* `push(x)`
* `pop()`
* `top()`
* `empty()`

### Example 1

**Input:**
`["MyStack","push","push","top","pop","empty"]`
`[[],[1],[2],[],[],[]]`

**Output:**
`[null,null,null,2,2,false]`

---
"""


class MyStack:
    def __init__(self):
        self.q1 = deque()
        self.q2 = deque()

    def push(self, x: int):
        self.q2.append(x)
        while self.q1:
            self.q2.append(self.q1.popleft())
        self.q1, self.q2 = self.q2, self.q1

    def pop(self):
        if self.empty():
            return None
        return self.q1.popleft()

    def top(self):
        if self.empty():
            return None
        return self.q1[0]

    def empty(self):
        return not self.q1

"""

## 3) Range Sum of BST

**Topic:** Tree, BST
**Difficulty:** Easy

Given the `root` node of a binary search tree and two integers `low` and 
`high`, return the sum of values of all nodes with a value in the 
inclusive range `[low, high]`.

### Example 1

**Input:**
`root = [10,5,15,3,7,null,18], low = 7, high = 15`
**Output:**
`32`

### Example 2

**Input:**
`root = [10,5,15,3,7,13,18,1,null,6], low = 6, high = 10`
**Output:**
`23`

---
"""


class TreeNode:
    def __init__(self, key=0):
        self.key = key
        self.left = None
        self.right = None


@print_return_value
def range_sum_bst(root: TreeNode, low: int, high: int) -> int:
    if root is None:
        return 0
    q = deque([root])
    total = 0
    while q:
        node = q.popleft()
        if low <= node.key <= high:
            total += node.key
        if node.left and node.key > low:
            q.append(node.left)
        if node.right and node.key < high:
            q.append(node.right)
        
    return total


root1 = create_bt([10, 5, 15, 3, 7, None, 18])
low, high = 7, 15

range_sum_bst(root1, low, high)


"""

## 4) Find the Difference

**Topic:** String Manipulation, Hashing
**Difficulty:** Easy

You are given two strings `s` and `t`.

String `t` is generated by random shuffling string `s` and then 
adding one more letter at a random position.

Return the letter that was added to `t`.

### Example 1

**Input:**
`s = "abcd", t = "abcde"`
**Output:**
`"e"`

### Example 2

**Input:**
`s = "", t = "y"`
**Output:**
`"y"`

---

## 5) Sort Characters By Frequency

**Topic:** Sorting, Hashing, Heap
**Difficulty:** Medium

Given a string `s`, sort it in decreasing order based on the 
frequency of the characters.

### Example 1

**Input:**
`s = "tree"`
**Output:**
`"eert"`

### Example 2

**Input:**
`s = "cccaaa"`
**Output:**
`"aaaccc"`

---

## 6) Find All Anagrams in a String

**Topic:** Sliding Window, Hashing, String Manipulation
**Difficulty:** Medium

Given two strings `s` and `p`, return an array of all the 
start indices of `p`'s anagrams in `s`.

### Example 1

**Input:**
`s = "cbaebabacd", p = "abc"`
**Output:**
`[0,6]`

### Example 2

**Input:**
`s = "abab", p = "ab"`
**Output:**
`[0,1,2]`

---

## 7) Trapping Rain Water

**Topic:** Two Pointers, Stack
**Difficulty:** Medium

Given `n` non-negative integers representing an elevation map where 
the width of each bar is `1`, compute how much water it can trap after raining.

### Example 1

**Input:**
`height = [0,1,0,2,1,0,1,3,2,1,2,1]`
**Output:**
`6`

### Example 2

**Input:**
`height = [4,2,0,3,2,5]`
**Output:**
`9`

---

## 8) Find the Duplicate Number

**Topic:** Slow and Fast Pointers, Array
**Difficulty:** Medium

Given an array of integers `nums` containing `n + 1` integers where 
each integer is in the range `[1, n]` inclusive, return the duplicate number.

You must solve the problem without modifying the array and using 
only constant extra space.

### Example 1

**Input:**
`nums = [1,3,4,2,2]`
**Output:**
`2`

### Example 2

**Input:**
`nums = [3,1,3,4,2]`
**Output:**
`3`

---

## 9) Remove Duplicates from Sorted List II

**Topic:** Linked List
**Difficulty:** Medium

Given the `head` of a sorted linked list, delete all nodes that have 
duplicate numbers, leaving only distinct numbers from the original list.

Return the linked list sorted as well.

### Example 1

**Input:**
`head = [1,2,3,3,4,4,5]`
**Output:**
`[1,2,5]`

### Example 2

**Input:**
`head = [1,1,1,2,3]`
**Output:**
`[2,3]`

---

## 10) Partition List

**Topic:** Linked List, Pointer Manipulation
**Difficulty:** Medium

Given the `head` of a linked list and a value `x`, partition it such 
that all nodes less than `x` come before nodes greater than or equal to `x`.

You should preserve the original relative order of the nodes in 
each of the two partitions.

### Example 1

**Input:**
`head = [1,4,3,2,5,2], x = 3`
**Output:**
`[1,2,2,4,3,5]`

### Example 2

**Input:**
`head = [2,1], x = 2`
**Output:**
`[1,2]`

---

## 11) Queue Reconstruction by Height

**Topic:** Greedy, Sorting
**Difficulty:** Medium

You are given an array of people, `people`, where `people[i] = [hi, ki]` 
represents the `i`th person of height `hi` with exactly `ki` people in 
front who have a height greater than or equal to `hi`.

Reconstruct and return the queue.

### Example 1

**Input:**
`people = [[7,0],[4,4],[7,1],[5,0],[6,1],[5,2]]`
**Output:**
`[[5,0],[7,0],[5,2],[6,1],[4,4],[7,1]]`

### Example 2

**Input:**
`people = [[6,0],[5,0],[4,0],[3,2],[2,2],[1,4]]`
**Output:**
`[[4,0],[5,0],[2,2],[3,2],[1,4],[6,0]]`

---

## 12) Search a 2D Matrix II

**Topic:** Matrix, Searching
**Difficulty:** Medium

Write an efficient algorithm that searches for a value `target` in an `m x n` 
integer matrix.

This matrix has the following properties:

* Integers in each row are sorted in ascending from left to right.
* Integers in each column are sorted in ascending from top to bottom.

### Example 1

**Input:**
`matrix = [
    [1,4,7,11,15],[2,5,8,12,19],[3,6,9,16,22],[10,13,14,17,24],[18,21,23,26,30]],
    target = 5`
**Output:**
`true`

### Example 2

**Input:**
`matrix = [
    [1,4,7,11,15],[2,5,8,12,19],[3,6,9,16,22],[10,13,14,17,24],[18,21,23,26,30]],
    target = 20`
**Output:**
`false`

---

## 13) Surrounded Regions

**Topic:** Matrix, Graphs
**Difficulty:** Medium

You are given an `m x n` matrix `board` containing letters `'X'` and `'O'`. 
Capture all regions that are 4-directionally surrounded by `'X'`.

A region is captured by flipping all `'O'`s into `'X'`s in that surrounded 
region.

### Example 1

**Input:**
`board = [
    ["X","X","X","X"],["X","O","O","X"],["X","X","O","X"],["X","O","X","X"]]`
**Output:**
`[["X","X","X","X"],["X","X","X","X"],["X","X","X","X"],["X","O","X","X"]]`

### Example 2

**Input:**
`board = [["X"]]`
**Output:**
`[["X"]]`

---

## 14) Populating Next Right Pointers in Each Node II

**Topic:** Tree, Queue, BFS
**Difficulty:** Medium

Given a binary tree:

```text
struct Node {
  int val;
  Node *left;
  Node *right;
  Node *next;
}
```

Populate each `next` pointer to point to its next right node. 
If there is no next right node, the `next` pointer should be set to `NULL`.

### Example 1

**Input:**
`root = [1,2,3,4,5,null,7]`
**Output:**
`[1,#,2,3,#,4,5,7,#]`

### Example 2

**Input:**
`root = []`
**Output:**
`[]`

---

## 15) Smallest Range Covering Elements from K Lists

**Topic:** K-way Merge, Heap
**Difficulty:** Medium

You have `k` lists of sorted integers in non-decreasing order.

Find the smallest range that includes at least one number from 
each of the `k` lists.

If there are multiple answers, return the one with the smallest 
left endpoint.

### Example 1

**Input:**
`nums = [[4,10,15,24,26],[0,9,12,20],[5,18,22,30]]`
**Output:**
`[20,24]`

### Example 2

**Input:**
`nums = [[1,2,3],[1,2,3],[1,2,3]]`
**Output:**
`[1,1]`

---

## Why this set helps

This batch intentionally strengthens the thinner areas from earlier:

* **k-way merge:** Q15
* **matrix:** Q12, Q13
* **queue:** Q2, Q14
* **slow/fast pointers:** Q8
* **string manipulation:** Q1, Q4, Q6
* **greedy + sorting:** Q11
* **stack beyond parentheses matching:** Q7

If you want, I can turn these 15 into a **7-day practice schedule ordered 
from easiest to hardest**.

"""
